spring:
  datasource:
    url: jdbc:postgresql://database-1.cbqcjwmtewyz.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: elephant
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate