version: "3.8"

services:
  project1:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://database-1.cbqcjwmtewyz.us-east-1.rds.amazonaws.com:5432/postgres
      - DB_USER=postgres
      - DB_PASS=elephant
    container_name: project1-container
    depends_on:
      - postgres
    volumes:
      - ./logs/application.log:/logs/application.log
      # IF THE FILE DOES NOT ALREADY EXIST, A FOLDER OF THAT NAME MIGHT BE CREATED

  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=elephant
    container_name: postgres-container
    volumes:
      - db-data:/var/lib/postgresql/data

  promtail:
    image: grafana/promtail:latest
    container_name: project1-promtail
    volumes:
      - ./promtail/promtail-docker-config.yml:/etc/promtail/docker-config.yaml
      - ./logs/application.log:/var/log/application.log
    command: "--config.file=/etc/promtail/docker-config.yaml"
    
  loki:
    image: grafana/loki:latest
    container_name: project1-loki
    ports:
      - 3100:3100
      
  grafana:
    image: grafana/grafana:latest
    container_name: project1-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    # persisting grafana settings
    ports:
      - 3000:3000
    depends_on:
      - loki
      
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    container_name: project1-prometheus
    
volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  db-data:
    driver: local